- src/main/java/petpple/kiwi/member/controller/Member/MemberController.java
- src/main/resources/static/css/member/sitter/sitterDiary.css
- src/main/resources/static/css/member/sitter/sitterInfo.css
- src/main/webapp/WEB-INF/views/member/memberInfoFsvcWaiting.jsp
- src/main/webapp/WEB-INF/views/member/memberMain.jsp
- src/main/webapp/WEB-INF/views/member/memberReviewPetChoice.jsp
- src/main/webapp/WEB-INF/views/member/memberReviewWritten.jsp
> ⚡️ :: (#14) member pet sitting info 링크 수정 - 소연

- src/main/java/petpple/kiwi/member/controller/Member/MemberController.java
- src/main/webapp/WEB-INF/views/member/memberInfoFsvcPast.jsp
- src/main/webapp/WEB-INF/views/member/memberInfoFsvcWaiting.jsp
- src/main/webapp/WEB-INF/views/member/memberInfoUsvcPast.jsp
- src/main/webapp/WEB-INF/views/member/memberInfoUsvcWaiting.jsp
- src/main/webapp/WEB-INF/views/member/memberInfoVsvcPast.jsp
- src/main/webapp/WEB-INF/views/member/memberInfoVsvcWaiting.jsp
- src/main/webapp/WEB-INF/views/member/memberSide.jsp
> 📑 :: (#17) 의뢰인 펫시팅 정보 페이지 생성

- src/main/java/petpple/kiwi/member/controller/User/UserController.java
- src/main/resources/static/css/user/userSignUp.css
- src/main/webapp/WEB-INF/views/user/userIdPwSearch.jsp
- src/main/webapp/WEB-INF/views/user/userIdSearch.jsp
- src/main/webapp/WEB-INF/views/user/userSignUp.jsp
> ⚡️ ::  (#15) 유저 회원가입 수정 - 현성

- src/main/java/petpple/kiwi/member/controller/User/UserController.java
- src/main/webapp/WEB-INF/views/user/userSignUp.jsp
> ⚡️ :: (#23) 유저 회원가입 수정 - 현성

- src/main/java/petpple/kiwi/member/controller/Member/MemberController.java
- src/main/webapp/WEB-INF/views/member/memberApplyForm.jsp
- src/main/webapp/WEB-INF/views/member/memberInfoUsvcIng.jsp
- src/main/webapp/WEB-INF/views/member/memberMain.jsp
- src/main/webapp/WEB-INF/views/member/memberSide.jsp
- src/main/webapp/WEB-INF/views/member/memberUsvcDetail.jsp
> ⚡️ :: (#22) 의뢰인 현재 의뢰중인 페이지 수정 및 생성

- src/main/webapp/WEB-INF/views/member/memberUsvcForm.jsp
> ⚡️ :: (#28)긴급 요청 서비스 등록 폼 수정 - 소연

- src/main/java/petpple/kiwi/member/controller/User/UserController.java
- src/main/webapp/WEB-INF/views/user/FAQ.jsp
- src/main/webapp/WEB-INF/views/user/header.jsp
- src/main/webapp/WEB-INF/views/user/userIdSearch.jsp
- src/main/webapp/WEB-INF/views/user/userPwSearch.jsp
- src/main/webapp/WEB-INF/views/user/userSignUp.jsp
> ⚡️ :: (#25) 유저 ID/PW 찾기 수정 - 현성

- build.gradle
- src/main/java/petpple/kiwi/member/domain/Member.java
- src/main/java/petpple/kiwi/member/repository/MemberMapper.java
- src/main/java/petpple/kiwi/member/service/MemberService.java
- src/main/resources/application.properties
- src/main/resources/mybatis-mapper/MemberMapper.xml
> 📑 :: (#26) sts gradle에 oracle, mybatis 추가 - 보영

- src/main/java/petpple/kiwi/member/controller/Member/MemberController.java
- src/main/java/petpple/kiwi/member/repository/MemberMapper.java
- src/main/resources/mybatis-mapper/MemberMapper.xml
- src/main/webapp/WEB-INF/views/member/sample.jsp
> ⚡️ ::  (#35) domain repository db test

- src/main/java/petpple/kiwi/member/controller/User/UserController.java
- src/main/java/petpple/kiwi/member/domain/User.java
- src/main/java/petpple/kiwi/member/repository/UserMapper.java
- src/main/resources/mybatis-mapper/UserMapper.xml
- src/main/webapp/WEB-INF/views/user/userSignUp.jsp
> 📑 :: (#32) db연동 유저 생성 - 현성

- src/main/java/petpple/kiwi/member/controller/User/UserController.java
- src/main/java/petpple/kiwi/member/domain/User.java
- src/main/resources/mybatis-mapper/UserMapper.xml
- src/main/resources/static/css/user/userSignUp.css
- src/main/webapp/WEB-INF/views/user/userSignUp.jsp
> ⚡️ :: (#42) user Mapper.xml 수정 - 현성

- src/main/java/petpple/kiwi/member/controller/Member/MemberToSitterController.java
- src/main/java/petpple/kiwi/member/domain/apply/Sitter.java
- src/main/java/petpple/kiwi/member/repository/apply/ISitterApply.java
- src/main/resources/application.properties
- src/main/resources/mybatis-mapper/SitterApply.xml
> ⚡️ :: (#38) 펫시터 지원하기 구현 - 동현 , 영관

- src/main/java/petpple/kiwi/member/controller/Member/MemberPetInsertController.java
- src/main/java/petpple/kiwi/member/domain/pet/Pet.java
- src/main/java/petpple/kiwi/member/repository/pet/IPetManage.java
- src/main/resources/mybatis-mapper/PetManage.xml
- src/main/resources/mybatis-mapper/SitterApply.xml
- src/main/webapp/WEB-INF/views/member/memberMyPetInsert.jsp
> 📑 :: (#45) pet insert - 영관

- src/main/java/petpple/kiwi/member/controller/Member/MemberController.java
- src/main/java/petpple/kiwi/member/controller/User/UserLoginController.java
- src/main/java/petpple/kiwi/member/domain/user/User.java
- src/main/java/petpple/kiwi/member/repository/user/UserMapper.java
- src/main/java/petpple/kiwi/member/service/user/UserService.java
- src/main/resources/mybatis-mapper/UserMapper.xml
- src/main/webapp/WEB-INF/views/user/userLogin.jsp
> ⚡️ :: (#49) user LoginController  수정 - 소연, 현성

- src/main/java/petpple/kiwi/member/controller/Member/MemberPetInsertController.java
- src/main/java/petpple/kiwi/member/domain/pet/Pet.java
- src/main/java/petpple/kiwi/member/repository/pet/IPetManage.java
- src/main/java/petpple/kiwi/member/service/member/ImgUpload.java
- src/main/resources/application.properties
- src/main/resources/mybatis-mapper/PetManage.xml
- src/main/webapp/WEB-INF/views/member/memberMyPetInsert.jsp
> ⚡️ :: (#50) 펫 추가 기능 구현 및 파일업로드 시스템 구현- 동현 ,영관 

- src/main/java/petpple/kiwi/member/controller/User/CheckController.java
- src/main/java/petpple/kiwi/member/controller/User/UserLoginController.java
- src/main/java/petpple/kiwi/member/repository/user/UserMapper.java
- src/main/java/petpple/kiwi/member/service/user/UserService.java
- src/main/resources/mybatis-mapper/UserMapper.xml
- src/main/webapp/WEB-INF/views/user/header.jsp
- src/main/webapp/WEB-INF/views/user/userContract.jsp
- src/main/webapp/WEB-INF/views/user/userMain.jsp
- src/main/webapp/WEB-INF/views/user/userSignUp.jsp
> ⚡️ :: (#53)  유저 페이지 경로 수정 - 현성, 소연

- src/main/java/petpple/kiwi/member/controller/Member/MemberPetInsertController.java
- src/main/java/petpple/kiwi/member/domain/pet/Pet.java
- src/main/java/petpple/kiwi/member/repository/pet/IPetManage.java
- src/main/resources/mybatis-mapper/PetManage.xml
- src/main/webapp/WEB-INF/views/member/memberMyPet.jsp
> ⚡️ :: (#56) pet 관리 수정 - 영관

- src/main/java/petpple/kiwi/member/controller/Member/MemberMainController.java
- src/main/java/petpple/kiwi/member/controller/User/UserLoginController.java
- src/main/java/petpple/kiwi/member/repository/user/UserMapper.java
- src/main/java/petpple/kiwi/member/service/user/UserService.java
- src/main/resources/mybatis-mapper/UserMapper.xml
- src/main/webapp/WEB-INF/views/user/userLogin.jsp
- src/main/webapp/WEB-INF/views/user/userMain.jsp
> ⚡️ :: (#58) 유저 세션 수정 - 현성, 소연

- src/main/resources/static/css/member/fsitter/fsitterMyProfile.css
- src/main/webapp/WEB-INF/views/member/fsitterMyProfile.jsp
- src/main/webapp/WEB-INF/views/member/fsitterMyProfileUpdate.jsp
> 📑 :: (#60) 펫시터 프로필 - 영관

- src/main/java/petpple/kiwi/member/controller/User/UserController.java
- src/main/webapp/WEB-INF/views/user/FAQ.jsp
- src/main/webapp/WEB-INF/views/user/header.jsp
- src/main/webapp/WEB-INF/views/user/userContract.jsp
- src/main/webapp/WEB-INF/views/user/userMain.jsp
> ⚡️ :: (#64) user 부분 매핑 수정 - 보영

- src/main/java/petpple/kiwi/member/controller/User/UserController.java
> ⚡️ ::  (#71) 유저 Controller의 IUserMapper 수정 - 현성

- src/main/webapp/WEB-INF/views/user/userSignUp.jsp
> 📑 :: (#74) 회원가입 페이지 수정 - 소연, 현성

- src/main/java/petpple/kiwi/member/controller/Member/MemberMainController.java
- src/main/java/petpple/kiwi/member/domain/member/Member.java
- src/main/java/petpple/kiwi/member/repository/member/MemberMapper.java
- src/main/resources/mybatis-mapper/MemberMapper.xml
- src/main/webapp/WEB-INF/views/member/memberMain.jsp
- src/main/webapp/WEB-INF/views/member/memberSide.jsp
- src/main/webapp/WEB-INF/views/user/userSignUp.jsp
> ⚡️ :: (#76) 펫시팅 현황 수정 미완 - 현성, 소연

- src/main/java/petpple/kiwi/member/controller/Member/MemberMainController.java
- src/main/java/petpple/kiwi/member/domain/member/Member.java
- src/main/java/petpple/kiwi/member/repository/member/MemberMapper.java
- src/main/java/petpple/kiwi/member/service/member/MemberService.java
- src/main/resources/mybatis-mapper/MemberMapper.xml
- src/main/webapp/WEB-INF/views/member/memberMain.jsp
> ⚡️ :: (#78) MemberMapper 수정 - 소연, 현성

- src/main/java/petpple/kiwi/member/controller/Member/MemberMainController.java
- src/main/java/petpple/kiwi/member/repository/member/MemberMapper.java
- src/main/resources/mybatis-mapper/MemberMapper.xml
- src/main/webapp/WEB-INF/views/member/memberMain.jsp
> 📑 :: (#80) memberMainController.java 수정 - 소연, 현성

- src/main/java/petpple/kiwi/member/controller/User/UserLoginController.java
- src/main/java/petpple/kiwi/member/domain/user/User.java
- src/main/java/petpple/kiwi/member/repository/user/IUserMapper.java
- src/main/webapp/WEB-INF/views/member/header.jsp
- src/main/webapp/WEB-INF/views/user/header.jsp
- src/main/webapp/WEB-INF/views/user/userLogin.jsp
> 📑 :: (#72) memberLogin 생성(미완) - 보영

- src/main/java/petpple/kiwi/member/controller/Member/MemberMainController.java
- src/main/java/petpple/kiwi/member/controller/Member/MemberPetsittingInfoController.java
- src/main/java/petpple/kiwi/member/domain/member/Member.java
- src/main/java/petpple/kiwi/member/repository/member/MemberMapper.java
- src/main/resources/mybatis-mapper/MemberMapper.xml
- src/main/webapp/WEB-INF/views/member/memberMain.jsp
- src/main/webapp/WEB-INF/views/member/memberSide.jsp
> ⚡️ :: (#94) 펫시팅 리스트 출력 수정 - 현성

- src/main/java/petpple/kiwi/member/controller/Member/MemberController.java
- src/main/java/petpple/kiwi/member/service/member/MemberService.java
- src/main/resources/mybatis-mapper/MemberMapper.xml
- src/main/webapp/WEB-INF/views/member/memberInfoVsvcWaiting.jsp
- src/main/webapp/WEB-INF/views/member/memberMain.jsp
> 📑 ::(#96) 필요한 controller 주석 해제 및 date 타입 수정 - 소연

- src/main/java/petpple/kiwi/member/controller/Member/MemberController.java
- src/main/webapp/WEB-INF/views/member/header.jsp
- src/main/webapp/WEB-INF/views/member/memberApply.jsp
- src/main/webapp/WEB-INF/views/member/memberInfoUsvcIng.jsp
- src/main/webapp/WEB-INF/views/member/memberInfoUsvcWaiting.jsp
- src/main/webapp/WEB-INF/views/member/memberMyInfo.jsp
- src/main/webapp/WEB-INF/views/member/memberReviewForm.jsp
- src/main/webapp/WEB-INF/views/member/memberReviewWritten.jsp
- src/main/webapp/WEB-INF/views/member/memberSvcTypeCho.jsp
- src/main/webapp/WEB-INF/views/member/memberUsvcDetail.jsp
- src/main/webapp/WEB-INF/views/user/header.jsp
> ⚡️ :: (#100) 헤더 수정 및 긴급 요청 서비스 등록 상세 내역  속성설정 

- src/main/java/petpple/kiwi/member/controller/Member/MemberFosterServiceController.java
- src/main/java/petpple/kiwi/member/domain/apply/ReviewProfile.java
- src/main/java/petpple/kiwi/member/domain/apply/Sitter.java
- src/main/java/petpple/kiwi/member/domain/fosterService/FosterService.java
- src/main/resources/mybatis-mapper/FosterSerivceMapper.xml
- src/main/webapp/WEB-INF/views/member/fsitterAjaxList.jsp
- src/main/webapp/WEB-INF/views/member/fsitterMyProfile.jsp
- src/main/webapp/WEB-INF/views/member/fsitterPetSitterList.jsp
> ⚡️ :: (#112) member FsitterList 수정 - 소연

- src/main/java/petpple/kiwi/member/controller/Member/MemberController.java
- src/main/java/petpple/kiwi/member/controller/Member/MemberUrgentServiceController.java
- src/main/webapp/WEB-INF/views/member/header.jsp
- src/main/webapp/WEB-INF/views/member/memberCareTypeCho.jsp
- src/main/webapp/WEB-INF/views/member/memberSvcTypeCho.jsp
- src/main/webapp/WEB-INF/views/member/memberUsvcDetail.jsp
- src/main/webapp/WEB-INF/views/member/memberUsvcForm.jsp
- src/main/webapp/WEB-INF/views/member/memberUsvcPetCho.jsp
> 📑 :: (#107) 긴급 서비스 관련 페이지 수정 및 매핑(미완) - 보영
